---
name: opentofu reusable workflow example

on:
  push:
    branches:
      - main
      - dev
      - stg
    paths:
      - "opentofu/**"
  pull_request:
    branches:
      - main
    paths:
      - "opentofu/**"

jobs:
  call-workflow:
    name: "Detect Changes"
    runs-on: ubuntu-latest
    permissions:
      contents: write # This is required for actions/checkout
      id-token: write # This is required for requesting the JWT
      pull-requests: write # This is required for commenting on PRs
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ref: ${{ github.event.pull_request.head.ref || github.ref }}
      - uses: dorny/paths-filter@v3
        id: changes
        with:
          filters: |
            triggered:
              - 'terraform/**'
    outputs:
      triggered: ${{ steps.changes.outputs.triggered }}

  opentofu_for_dev:
    name: "OpenTofu job for Development branch"
    needs: call-workflow
    if: ${{ needs.call-workflow.outputs.triggered == 'true' && github.ref == 'refs/heads/dev' }}
    uses: jdfant/github-actions/.github/workflows/opentofu-aws.yaml@main
    with:
      AWS_REGION: 'us-west-1'
      ACCT_NUM: '012345678910'
      ACCT_NAME: 'opentofu-test-account'
      WORK_DIR: 'opentofu'

  opentofu_for_stg:
    name: "OpenTofu job for Stage branch"
    needs: call-workflow
    if: ${{ needs.call-workflow.outputs.triggered == 'true' && github.ref == 'refs/heads/stg' }}
    uses: jdfant/github-actions/.github/workflows/opentofu-aws.yaml@main
    with:
      AWS_REGION: 'us-west-2'
      ACCT_NUM: '012345678910'
      ACCT_NAME: 'opentofu-test-account'
      WORK_DIR: 'opentofu'
...